# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_desc',
            field=models.CharField(max_length=255, verbose_name='Tag description'),
        ),
    ]
